what are tokens?
Tokens are the small unit in the python...
1.identifiers:Identifiers is a name of variables or functions or class
  .variable
  example:
	num = 'python'
	print(type(num))
  .functions
  example:
	def add_(a,b):
	    print(a+b)
	add_(4,5)
  .class
  example:
	class details:
	    pass
	per_1 = details

2.Keywords:Keywords that are already saved or defined in python for an specified reason to run..
 example:
 1.if
 2.else
3.for
4.while
5.return
6.print 

3.Literals : Literals are nothing but it is a data type
	     Literals are the data types that need to be stored in variables...
example:
	num = 90
	name = 'harshini'
	
4.Operators
	+ , - , *, = ,/ , //
5.Statements:
	Statements are the instructions given to the program ...

	example:
		age = 20
		if age >= 18:
		    print(age)
6.Comments:Once commands are opened the lines inside will never execute in python file.
  They are 2 types of commands
1.Single line command (#) - It is used to command only one line.
	example:
		age = 20
		if age >= 18: # it checks age is greater or equal.
		    print(age)

2.Multi line commands ('''''' , """ """ ) (--------) - 



7. variables rules
 Bad ways
	.can't use number at 1st position
	.can't use special characters anywhere
	.can't use space
	.can't use keywords
EXAMPLE:
	2num = 90
	$num = 89
	n um  = 97
	if = 97
Good ways:
	.small letters and cap letters, (_) under
example1:
	num_1 = 90
	Num_2 = 82
example2:
a = {'name':'harshini'
     'AC_NUM' : '48926043252782'}
b = {'name':'harshi'
     'AC_NUM' : '48926043252724'}
c = {'name':'harshitha'
     'AC_NUM' : '48926043252732'}

SBI_harshi_details = {'name':'harshi'
     'AC_NUM' : '48926043252724'}
ICICI_harshini_details = {'name':'harshi'
     'AC_NUM' : '48926043252724'}

example 3:
	num = 90
	print(num)
	num_3, num_2 = 56,90


SWAPPING OF TWO VARIABLES:
EXAMPLE:
a , b = 45,67
print('a=' ,a)
print('b=' ,b)
a, b = b, a
print('a=' ,a)
print('b=' ,b)


